(function() {
    'use strict';
    var WebApp = angular.module('WebApp', []);
    WebApp.controller('ContactController', ContactController);

    /** ngInject */
    function ContactController() {
        var vm = this;
        vm.contactDetails = [{
            "login": "dattatrey93",
            "id": 13445492,
            "avatar_url": "https://avatars.githubusercontent.com/u/13445492?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dattatrey93",
            "html_url": "https://github.com/dattatrey93",
            "followers_url": "https://api.github.com/users/dattatrey93/followers",
            "following_url": "https://api.github.com/users/dattatrey93/following{/other_user}",
            "gists_url": "https://api.github.com/users/dattatrey93/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dattatrey93/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dattatrey93/subscriptions",
            "organizations_url": "https://api.github.com/users/dattatrey93/orgs",
            "repos_url": "https://api.github.com/users/dattatrey93/repos",
            "events_url": "https://api.github.com/users/dattatrey93/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dattatrey93/received_events",
            "type": "User",
            "site_admin": false,
            "name": "Narottam Dattatrey",
            "company": null,
            "blog": null,
            "location": "Bangalore",
            "email": "dattatrey93@gmail.com",
            "hireable": true,
            "bio": "love to code",
            "public_repos": 9,
            "public_gists": 0,
            "followers": 4,
            "following": 4,
            "created_at": "2015-07-22T03:56:16Z",
            "updated_at": "2016-12-17T18:29:44Z"
        }, {
            "login": "mangalaman93",
            "id": 2542340,
            "avatar_url": "https://avatars.githubusercontent.com/u/2542340?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mangalaman93",
            "html_url": "https://github.com/mangalaman93",
            "followers_url": "https://api.github.com/users/mangalaman93/followers",
            "following_url": "https://api.github.com/users/mangalaman93/following{/other_user}",
            "gists_url": "https://api.github.com/users/mangalaman93/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mangalaman93/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mangalaman93/subscriptions",
            "organizations_url": "https://api.github.com/users/mangalaman93/orgs",
            "repos_url": "https://api.github.com/users/mangalaman93/repos",
            "events_url": "https://api.github.com/users/mangalaman93/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mangalaman93/received_events",
            "type": "User",
            "site_admin": false,
            "name": "Aman Mangal",
            "company": "Georgia Tech",
            "blog": "http://amanmangal.me/",
            "location": "Atlanta",
            "email": "mangalaman93@gmail.com",
            "hireable": true,
            "bio": null,
            "public_repos": 51,
            "public_gists": 10,
            "followers": 19,
            "following": 32,
            "created_at": "2012-10-12T05:33:13Z",
            "updated_at": "2016-12-09T05:46:06Z"
        }, {
            "login": "amanmangal",
            "id": 4545503,
            "avatar_url": "https://avatars.githubusercontent.com/u/4545503?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/amanmangal",
            "html_url": "https://github.com/amanmangal",
            "followers_url": "https://api.github.com/users/amanmangal/followers",
            "following_url": "https://api.github.com/users/amanmangal/following{/other_user}",
            "gists_url": "https://api.github.com/users/amanmangal/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/amanmangal/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/amanmangal/subscriptions",
            "organizations_url": "https://api.github.com/users/amanmangal/orgs",
            "repos_url": "https://api.github.com/users/amanmangal/repos",
            "events_url": "https://api.github.com/users/amanmangal/events{/privacy}",
            "received_events_url": "https://api.github.com/users/amanmangal/received_events",
            "type": "User",
            "site_admin": false,
            "name": "Aman Mangal",
            "company": "Chronus Corporation",
            "blog": "www.cse.iitb.ac.in/~amanmangal",
            "location": "Chennai",
            "email": "aman.mangal@chronus.com",
            "hireable": null,
            "bio": null,
            "public_repos": 0,
            "public_gists": 0,
            "followers": 0,
            "following": 0,
            "created_at": "2013-05-28T04:52:21Z",
            "updated_at": "2016-02-27T08:52:36Z"
        }, {
            "login": "ashish",
            "id": 35478,
            "avatar_url": "https://avatars.githubusercontent.com/u/35478?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ashish",
            "html_url": "https://github.com/ashish",
            "followers_url": "https://api.github.com/users/ashish/followers",
            "following_url": "https://api.github.com/users/ashish/following{/other_user}",
            "gists_url": "https://api.github.com/users/ashish/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ashish/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ashish/subscriptions",
            "organizations_url": "https://api.github.com/users/ashish/orgs",
            "repos_url": "https://api.github.com/users/ashish/repos",
            "events_url": "https://api.github.com/users/ashish/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ashish/received_events",
            "type": "User",
            "site_admin": false,
            "name": 'mohit',
            "company": null,
            "blog": null,
            "location": null,
            "email": null,
            "hireable": null,
            "bio": null,
            "public_repos": 1,
            "public_gists": 0,
            "followers": 3,
            "following": 0,
            "created_at": "2008-11-19T17:59:16Z",
            "updated_at": "2014-06-05T09:41:37Z"
        }];
    };
})();
